name: ci
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Caching dependency
        uses: actions/cache@v3.2.5
        with:
          path: |
            ~/.cache
            ~/.npm
          key: dependencies-v1-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run: npm ci

      - name: Build APP
        run: npm run build

      - name: Starting App and run E2E tests
        run: npm run e2e
        
      - name: Download screenshots and videos folder
        uses: actions/upload-artifact@v3.1.2 
        if: always()
        with:
    # Artifact name
          name: test-artifacts # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: 
            /home/runner/work/cy-ci-example/cy-ci-example/cypress/videos/
            /home/runner/work/cy-ci-example/cy-ci-example/cypress/screenshots/
          # The desired behavior if no files are found using the provided path.
      # - name: Start the app
      #   run: npm start &

      # - name: Wait for site url
      #   run: npx wait-on http://localhost:8080

      # - name: cypress tests execute
      #   run: npm run cy:run
