name: ci
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      -name: Caching dependency
        uses: actions/cache@v2
        with:
          path:
          ~/.cache
          ~/.npm
          key: dependencies-v1-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run: npm ci

      - name: Build APP
        run: npm run build

      - name: Start the app
        run: npm start &

      - name: cypress tests execute
        run: npm run cy:run
